### ISSUE TITLE
Фотка в ЛК

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#10]
если фотка в лк по высоте больше чем надо, все налазит друг на друга изза ... ясно чего. 
И как фиксить?
![2013-10-03_023323](https://f.cloud.github.com/assets/3214290/1258007/03245092-2bb3-11e3-8945-6abbf027b931.png)

**Comment by viktor-melnikov** [comment]
Хуль она вобще растягивается... там же фиксир высота

**Comment by roquie** [comment]
Я также подумал когда тетюшин открыл лк у себя в кабинете )

**Comment by viktor-melnikov** [comment]
Пох, дома подставлю его фотку в дебагере и попробую исправить...
А на счет менюшки, ее моно тож абсолютной сделать и все норм будет

**Comment by roquie** [comment]
уж лучше в бд ссылку кинь )

**Comment by viktor-melnikov** [comment]
Да нахуй в бд) в свой акк сувать его фотку...

**Comment by roquie** [comment]
просто чтобы с дебагером не мучаться )

**Comment by viktor-melnikov** [comment]
а ты не знал что ли?) Я тож могу твои редактировать)

**Comment by roquie** [comment]
вот черт

ололошка
