### ISSUE TITLE
плэйсхолдер

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#11]
баг это или фитча, но при вводе в инпут значения равного плейсходеру, пишет "Заполниче это поле", при этом удаляет это слово. )

Например, введи "Имя", в контактах и поймешь о чем речь ))

**Comment by viktor-melnikov** [comment]
ну смотри, тот плейсхолдер он как бы подставляет значение в value, т.е. оно пустым в принципе не будет никогда. поэтому чтобы проверить типа на пустоту, идёт проверка чтобы значение не было равно плейсхолдеру

**Comment by roquie** [comment]
дык это и так понятно, все равно досадно

**Comment by viktor-melnikov** [comment]
ну зато кроссбраузерно. да и не думаю, что у кого-то имя "Имя" ))

**Comment by roquie** [comment]
у китайцев имя мб вообще "Спайдер мэн", так что я тут не был бы уверен)) а у нас они ходят в автошколу))

**Comment by roquie** [comment]
ну а так, болт как болт

**Comment by viktor-melnikov** [comment]
ЛОЛ) ну если блин попадётся китаец с именем "Имя", мне его жаль))) не сможет он подать заявление и отправить на главной письмо))) и того доступ в автошколу через наш сайт, для китайцев закрыт)))
