### ISSUE TITLE
добей это как он просил

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#12]
блок обычный по центру типа нотификации (информер от бутстрапа), исчезает через пару сек ... ну ты помнишь

``` js
$(function() {
     $(window).on('load', function() {
        alert('Вы были успешно зарегистрированы. На вашу почту отправлены данные для входа.');
       });
    });
```

**Comment by viktor-melnikov** [comment]
я думал иначе, чтоб он не исчезал, а чтобы короче в правом верхнем углу крестик и если нажать то он пропадёт и всё. так удобнее, а то вдруг юзер не успеет прочесть...

**Comment by roquie** [comment]
все он там успеет, если ему перед лицом вывести

**Comment by roquie** [comment]
и не надо в правом верхнем углу, тупо по центру и вверху типа как алерт, но чтобы закрывался он сам - тут уж точно увидит )

**Comment by roquie** [comment]
хотя, мб вообще вывести нотификацию с исчезновением и все о_О

**Comment by roquie** [comment]
тока таймер на 5 сек

**Comment by viktor-melnikov** [comment]
ты мои каменты через слово что ли читаешь)))

чтобы короче в правом верхнем углу крестик

крестик в углу а не сам алерт... алерт будет по центру.
на счёт нотификации хз, я так вчера предлагал же ( ты 100% не помнишь этого:) ), ты сказал ненене

**Comment by roquie** [comment]
Ну раз упрекать начал.
Точно также как и ты мои, через слово. 
А вообще, говори иначе, чтобы тебя понимали какие алерты и где ты их выводить собрался. 
Т.к. то сообщение весьма двояко. А крестики у нас всегда в правом верхнем углу.

**Comment by viktor-melnikov** [comment]
)) да окок)

**Comment by roquie** [comment]
это сделано?

**Comment by viktor-melnikov** [comment]
не сделано( я сделаю
