### ISSUE TITLE
Отправка почты на главной

### ISSUE THREAD

**Issue by viktor-melnikov** [roquie/autoschool#13]
раз ты там файлики правишь, убери заглушку на серваке для отправки почты на главной

**Comment by roquie** [comment]
ее там нет, просто $result вернул false, а почему так - хз

**Comment by viktor-melnikov** [comment]
лол так и думал)) а почему это оч хороший вопрос)))

**Comment by roquie** [comment]
все отправляется?

**Comment by viktor-melnikov** [comment]
не отправляется на тк, но отправляется на mpt.ru

**Comment by roquie** [comment]
о_О от хостинга и домена это никак не должно зависеть, хотя насчет 1го я сомневаюсь

**Comment by viktor-melnikov** [comment]
я думаю что-то с хостингом связано... чё-то бегет шалит в последнее время...

**Comment by roquie** [comment]
ну да, там отправляет, а в другом месте не хочет ... )

**Comment by viktor-melnikov** [comment]
тогда хуй его знает что это)) но с главной токо на мпт отправляется))
