### ISSUE TITLE
Утверждение данных договора

### ISSUE THREAD

**Issue by viktor-melnikov** [roquie/autoschool#15]
Возможность утверждения договора со стороны админа, после чего редактировать данные в лк в договоре нельзя.
запили эту штуку. мб в настройках лучше будет (в админке есстественно)

**Comment by roquie** [comment]
запилится но позже

**Comment by roquie** [comment]
Утверждение данных договора идет до зачисления в группу, сначала вывод всех необходимых слушателей, справа галка "договор утвержден" и при клике, анимашка от квери.
Галку ставим в бд, в табл users, как поле is_approved, ну а от него зависит возможность или не возможность редактировать договор + заявление.

## Делаем?

**Comment by viktor-melnikov** [comment]
да, делаем. это обязательно.

**Comment by roquie** [comment]
осталось тока в админке функционал запилить
