### ISSUE TITLE
Сделать нормальный лоадер в лк 

### ISSUE THREAD

**Issue by viktor-melnikov** [roquie/autoschool#16]

**Comment by viktor-melnikov** [comment]
лоадер сделан.

**Comment by roquie** [comment]
эм, я увидел тока изменение размеров )

**Comment by viktor-melnikov** [comment]
а что тебе ещё надо Оо

**Comment by roquie** [comment]
размести по центру и перенос строк сделай как в твиттере

**Comment by roquie** [comment]
впрочем это мелочи, в посл очередь ...
