### ISSUE TITLE
перенеси lk в app

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#17]
сам себе =\

**Comment by viktor-melnikov** [comment]
зачееем??? пусть будет как модуль, так норм же. логическое разделение имеется хотя бы

**Comment by roquie** [comment]
логическое и без того будет, т.е. подпапку для Lk создадим. А держать модуль нет никакого смысла =\
Там уже все модели не нужны например, контроллеры перенести со вьюшками

**Comment by viktor-melnikov** [comment]
эх, печально. так был как отдельный модуль...

**Comment by roquie** [comment]
отдельный модуль?) не смеши он давно им перестал быть
