### ISSUE TITLE
та фишка для распределения новых слушателей по группам

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#18]
ну ты помнишь о чем мы говорили и что ты предлагал.
listbox => combobox
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; listbox

**Comment by viktor-melnikov** [comment]
да да, сделаю
