### ISSUE TITLE
Лк + заявление

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#2]
Вкладка реги + модалка для входа )

**Comment by viktor-melnikov** [comment]
так, на счёт модалки.
этот вход будет для юзеров, или и для админа тоже?

**Comment by roquie** [comment]
Онли юзеры, для админа над сделать /admin

**Comment by viktor-melnikov** [comment]
ок, токо мб не модалка всё  же) а попап?)

**Comment by roquie** [comment]
Похуй както. давай попап

**Comment by roquie** [comment]
И еще работы сам себе придумай ))

**Comment by viktor-melnikov** [comment]
у меня работы дохуя с квери для реги входа и т.д....
