### ISSUE TITLE
изменения пароля в настройках 

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#20]
что еще помимо этого расположить в настройках?

**Comment by viktor-melnikov** [comment]
мб мыло сменить, вдруг пароль от мыла потерял. а ведь сообщения будут на это мыло приходить

**Comment by roquie** [comment]
смена email тогда будет возможна только в том случае, если подтвердят намерения через текущее

**Comment by viktor-melnikov** [comment]
так а если я например забыл пароль от текущего мыла и хочу поэтому сменить его, как я тебе подтвержу что-то?)
может быть тогда каждое действие подобное запрашивать пароль?

**Comment by roquie** [comment]
ох лол, так даже проще.

**Comment by viktor-melnikov** [comment]
ну а чё, ведь по сути доступ к акку по паролю, т.е. все важные действия делать по паролю и всё

**Comment by roquie** [comment]
свою часть сделал, время jquery :)

**Comment by roquie** [comment]
> упс

**Comment by viktor-melnikov** [comment]
лол, время jquery=) ну ок, вызов принят)))
