### ISSUE TITLE
админка: переход по вкладкам в настройках как в лк

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#24]
1. в адресной строке .ru/admin/settings#smtp
2. в коде перекинуть класс active на ту вкладку которая указана в 1
3. profit !!! 
4. **^_^**

**Comment by viktor-melnikov** [comment]
епать... надо мне плагин захерачить под это дело. устал повторять один и тот же код 100 раз...

**Comment by roquie** [comment]
это хорошо бы, но тут по плагин не сделаешь, тут код под бутстрап будет

**Comment by viktor-melnikov** [comment]
Поч под бутстрап о_О

**Comment by viktor-melnikov** [comment]
ты про фреймворк Bootstrap или про файлик коханы bootstrap?))

**Comment by roquie** [comment]
1

**Comment by viktor-melnikov** [comment]
Я могу написать универсальный) просто к ссылкам добавлять идентификатор какой-нить и все

**Comment by roquie** [comment]
я знаю что ты можешь, одно дело написать 10 строк на разбор адр.строки+при онклике перебросить active, другое дело написать плагин, тогда больше времени уйдет. Нафига его тратить?

**Comment by viktor-melnikov** [comment]
это-то да, но вот когда таких строк много, уж лучше плагин иметь.
да и зачем тогда плагин ajax?) тож 15 строк всего лишь))

**Comment by roquie** [comment]
ох, короче чтобы работало

**Comment by viktor-melnikov** [comment]
сделал всё ахуенчик
