### ISSUE TITLE
админка: загрузка файлов

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#25]
в админке есть скрипт для загрузки файлов на сервак, необходимо чтобы оно стучалось мне в экшен с массивом $_FILES

**Comment by roquie** [comment]
эт тебе задание было, а не мне

**Comment by viktor-melnikov** [comment]
эм, наскоко я помню) ты сказал сам запилешь=)

**Comment by roquie** [comment]
тут несколько заданий, эта часть касается тебя. А сам я запилю на пхп. Ты мне массив files кинь то на метод аплоада

**Comment by viktor-melnikov** [comment]
ну я попробую, над плагин найти нормальный. чтобы кидал. потому как ajax не передаёт

``` php
$_FILES
```

**Comment by roquie** [comment]
он не передает, он отправляет пост запрос с содержимым input type="file", вот это мне надо

**Comment by roquie** [comment]
тебе просто запилить кнопку "отправить" и послать пост запрос по адресу

**Comment by viktor-melnikov** [comment]
он вообще не видит поля где
type="file"
