### ISSUE TITLE
админка: ставить галочки для не утвержденных слушателей

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#28]
1. вывести на главной в админке слушателей
2. ставить им галочки ... что они утверждены
3. после чего определить их в группу

__
ps. делать ли поэтапно как он просил? хм. а если не всех слушателей хочет утвердить и не всех распределить по группам.

**Comment by viktor-melnikov** [comment]
на счёт этапов идея прикольная, и визуально всё видно, слушатель может спросить я вам всё принёс, а тетюшин просто посмотреть по этапам что сдано, а что нет.
если сделаем это будет просто ахуенно)))

**Comment by roquie** [comment]
он предлагал сделать этап для каждого слушателя - нннах это..., проще статус показывать

**Comment by viktor-melnikov** [comment]
Стут не круто
Вот отображать что сдано прикольно было б)там всего 3 поля в бд...
Заявление договор, фотки, паспорт. Все

**Comment by viktor-melnikov** [comment]
И кстати можно же не прогресс бар, а просто типа колонки таблицы и ставить галочку либо крестик (сдал или нет)

**Comment by roquie** [comment]
еще 3 поля в табл. юзеров делать? 

> убиться можно

**Comment by viktor-melnikov** [comment]
Моно 1 поле и в него сериализованный массив где указать договор, заявлени и паспорт. И ставить им сдано или не сдано

**Comment by roquie** [comment]
Уже решили как :) 
Без всяких сериализованных массивов ))

**Comment by viktor-melnikov** [comment]
ты смотри когда я это писал) это ты не сразу не увидел...

**Comment by roquie** [comment]
я это увидел сразу когда было написано, а ответ был просто так для галочки. Хватит думать не в ту сторону о_О

**Comment by roquie** [comment]
Тем более гитхаб спамит почту + уведомлялки показывает, как тут можно пропустить?

**Comment by viktor-melnikov** [comment]
я пропускаю=) почему-то на моб уведомления о письмах на почте не приходят :)

**Comment by roquie** [comment]
о_О
