### ISSUE TITLE
админка: генерация экселя всяких там слушателей по группам

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#31]
над глянуть тот софт на флешке для лучшего понимания

**Comment by viktor-melnikov** [comment]
сможешь, глянь=))) поставь для начала FireBird=)
лучше взять попросить чтобы он нам дал в его проге полазить и всё.

**Comment by roquie** [comment]
у меня он не пошел ни под каким предлогом, до сих пор удалить не могу остатки сраного interbase'a

а у тя все было нормик ^_^

**Comment by roquie** [comment]
да и вообще софт тот использует аксес, а на прогу пирожкова начхать из-за интербэйса

**Comment by viktor-melnikov** [comment]
так а разве у нас есть его прога? у нас же вроде токо прога пирожкова, не?

**Comment by roquie** [comment]
нет, он давал тебе флешку со всеми файлами и нормальной прогой, ты потом все скопировав, вернул ему обратно - я точно помню.

**Comment by viktor-melnikov** [comment]
да эт я тоже помню. ну ок я попробую...

**Comment by roquie** [comment]
ок.
---------------------
в issue есть слева лэйблы, нажми на "fast" - это те что над выполнить в первую очередь как можно скорее ))
"future" - на будущее, типа то что будет сделано после "new"
"new" - все задания, которые еще не выполнены.

**Comment by viktor-melnikov** [comment]
капитанчик ты мой=)

**Comment by roquie** [comment]
....
