### ISSUE TITLE
админка: похожий интерфейс, как у той проги, сделать на главной сайта.

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#33]
с меня вьшки, с тебя 
скрины программы:
- mainmenu
- главное окно
- вспомогательные окна

и это все залить на диск.

**Comment by viktor-melnikov** [comment]
как я тебе щас сделаю скрины) думаешь у меня есть файрбёрд?)))

**Comment by roquie** [comment]
ответил уже ...

**Comment by viktor-melnikov** [comment]
скрины на диске видел???

**Comment by roquie** [comment]
да, все ахрененно сделал :)

**Comment by viktor-melnikov** [comment]
да лан) ты всё сделал?))

**Comment by roquie** [comment]
да, тут же главная страница

**Comment by roquie** [comment]
https://github.com/Roquie/autoschool/issues/34
