### ISSUE TITLE
Раскидать css и js согласно смыслу по папкам в media

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#37]

**Comment by roquie** [comment]
чет я не понял твоей логики )

**Comment by viktor-melnikov** [comment]
всмысле
4 папки:
general - файлы которые юзают все части сайта
admin - это то что юзается на страницах админки
main - тут то что на страницах главного сайта
lk - а тут чисто лк

**Comment by roquie** [comment]
ок
