### ISSUE TITLE
ajax.js; LK -> settings -> жмакай мышкой на инпуты

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#39]

**Comment by roquie** [comment]
смотри

**Comment by roquie** [comment]
и еще у меня весьма ужасно отображается главная в админке
![2013-11-09 4 03 43](https://f.cloud.github.com/assets/3214290/1506343/0d494eec-4922-11e3-8205-00fc46c4a388.png)

**Comment by roquie** [comment]
wtf?

**Comment by viktor-melnikov** [comment]
ой лол) чисти кэш))) эт я хз...

**Comment by viktor-melnikov** [comment]
исправлено
