### ISSUE TITLE
Админка

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#4]
Подумай как запилить в отправке почты,  отправку сообщений в лс каждому, и отправку по группе

**Comment by roquie** [comment]
Стопку идей и если над реализацию )

**Comment by viktor-melnikov** [comment]
ну как, делать 2 таблицы. одна будет для сообщений по группе, вторая каждому юзеру.
что касаемо чата о котором он говорил это на диплом если успеем то реализуем...
а на счёт как запилить, сделать моно чекбокс типа отправить группе. если он поставлен, то в поиск где выбор студентов, там выводить список групп и всё.

**Comment by roquie** [comment]
Круто, особенно в конце

**Comment by viktor-melnikov** [comment]
ну и збс) но эта первая идея) мб додумать её ещё)

**Comment by roquie** [comment]
Не хочу отправлять файлы в лк студентам ))) геморрой ...

**Comment by roquie** [comment]
Хотя всеголишь путь передать до файла в папке аплоад,но нет, лень ...

**Comment by viktor-melnikov** [comment]
я так подумал
раз теперь есть лк
зачем нам делать отправку файлов в админке)) они и так всё могут скачать в лк своём...

**Comment by roquie** [comment]
Ну типа оповестить по почте, чтоб в лк зашли )))
