### ISSUE TITLE
LK: сделать норм лоадер

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#40]
сколько уже времени прошу?

**Comment by viktor-melnikov** [comment]
сделал, коммит будет позже

**Comment by roquie** [comment]
Ура! Ура! Ура!

**Comment by viktor-melnikov** [comment]
лол) да я тебе прям праздник смотрю устроил) и лоадер и менюшка ;)

**Comment by roquie** [comment]
ага, праздник. Лучше б сразу сделал и забыл))
