### ISSUE TITLE
LK: выровнять список меню

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#41]

**Comment by viktor-melnikov** [comment]
куда его выравнять о_О, скрин того как у тя всё это гавно отображается

**Comment by roquie** [comment]
![2013-11-09 20 05 46](https://f.cloud.github.com/assets/3214290/1506958/faea828e-4958-11e3-9e01-14bc1e89f676.png)

**Comment by viktor-melnikov** [comment]
Сделано, вот результат:

![image](https://f.cloud.github.com/assets/5323465/1526209/4342497e-4be1-11e3-968d-a756582c5d12.png)

**Comment by roquie** [comment]
Оно свершилось ) молодец))

**Comment by viktor-melnikov** [comment]
=) ты бы видел через какую жопу я выравнял)))

**Comment by roquie** [comment]
до этого я тоже их равнял череж одно место, поэтому норм ^___^
