### ISSUE TITLE
ОШИБКА!!!

### ISSUE THREAD

**Issue by viktor-melnikov** [roquie/autoschool#49]
Нельзя называть имя файла контроллера два раза с большой буквы!!!
ошибка в MainPage.php
он тупо на беге не находит такой файл, т.к. по умолчанию токо первая буква заглавная.
переименовал на бегете в Mainpage.php всё работает. ты уж там поменяй и сделай коммит..
p.s. видишь я не лезу в твой код =)

**Comment by roquie** [comment]
О боже ...

**Comment by viktor-melnikov** [comment]
Не о боже) а статусы не грузятся на главной админки на беге)

**Comment by roquie** [comment]
git походу неверно объединил файлы, эти баги уже как нескоко дней назад были поправлены
