### ISSUE TITLE
подправить баг с иконками твиттера в лисе

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#5]
![2013-09-27_013456](https://f.cloud.github.com/assets/3214290/1221842/8c0e9698-26f3-11e3-9c3d-a71cc0a52719.png)

не отображается тока в лисе, че так о_О, чем ему твиттер не угодил

**Comment by roquie** [comment]
нашел впринципе http://wpvkp.com/font-awesome-doesnt-display-in-firefox-maxcdn/
зава поправлю

**Comment by viktor-melnikov** [comment]
ну так ты поправил уже?)) моно закрывать this issue?)
просто у меня-то в лисе всё норм. поэтому я в принципе не смогу поправить)

**Comment by roquie** [comment]
вот черт у меня и на маке тоже самое проявляется о_О

**Comment by roquie** [comment]
над проверить, должно быть все ок
