### ISSUE TITLE
Подправить валидацию на сервере при добавлении данных

### ISSUE THREAD

**Issue by viktor-melnikov** [roquie/autoschool#54]
в поле адреса могут быть тире, запятые, точки и пробелы.
![2013-12-05_174041](https://f.cloud.github.com/assets/5323465/1682811/e32649b2-5db2-11e3-855b-3554563f4b64.png)
![2013-12-05_174108](https://f.cloud.github.com/assets/5323465/1682813/f585e0cc-5db2-11e3-9dc7-1f6825142ca1.png)

**Comment by roquie** [comment]
качать посл изменения а потом говорить о багах
