### ISSUE TITLE
везде: не работает боковая панель

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#56]
конфликт в js между стандартной модалкой и плагином для выдвижения панельки. 
_
причину смотри в файле js/main/main.js

**Comment by viktor-melnikov** [comment]
ЩТА БЛЯТЬ?) всё же работало))) и с модалкой....
да и если трабл в модалке, то не работало бы только на главной

**Comment by viktor-melnikov** [comment]
стоп, а что за модалка?? её на главной же нету вообще

**Comment by roquie** [comment]
Новости в мэйне глобальны, посмотреть ты их могешь везде. Поэтому они везде мешают любой модалке в мэйне. Модалка нах-ся в лк -> загрузки. 

Код модалки тут не причем, тк разрабы bootstrap js не идиоты. Надо найти конфликт в плагине новостей который я закомментил.

**Comment by viktor-melnikov** [comment]
странно... я помню когда каптча была в модалке новости работали на збс

**Comment by roquie** [comment]
Работало потому что я писал свой велосипед для каптчи на квери

**Comment by viktor-melnikov** [comment]
нихуя) там был стандартный modal от бутстрапа
