### ISSUE TITLE
знак рубля поправить, чтоб четко было на винде

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#58]

**Comment by viktor-melnikov** [comment]
да уж пж)

**Comment by roquie** [comment]
вернул старый ламповый - Р.

**Comment by viktor-melnikov** [comment]
не ну так не круто) давай картиночкой пока вставим новый символ рублика. чтоб прям кашерно было)

**Comment by roquie** [comment]
Пока похуй на эт. Не критично.
