### ISSUE TITLE
баг с лисой, при клике на меню

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#6]
![2013-09-27_013737](https://f.cloud.github.com/assets/3214290/1221860/eb33602c-26f3-11e3-92a8-8e12bab8e837.png)
где-то собака зарыта

**Comment by viktor-melnikov** [comment]
это не баг, это механизмы лисы, в вк также всё происходит..
максимум можно попробовать :active и там короче убрать
outline: none;
background: none;
как-то так

**Comment by roquie** [comment]
то что он выделяет вокруг, это я знаю про лису. А вот background: none; ничем тебе не поможет :)

**Comment by viktor-melnikov** [comment]
тогда никак это не убрать...

**Comment by roquie** [comment]
утопичный ты, убрать можно, но хз где это задано в бутстрапе. Т.к. не inverse navbar - такого цвета

**Comment by roquie** [comment]
при просмотра кода в веб-инспекторе - ничерта не вижу где оно задано

**Comment by roquie** [comment]
fixed;
