### ISSUE TITLE
добавление записей в твиттер из pageslide  панели в админке

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#63]

**Comment by viktor-melnikov** [comment]
так стоп. Панель новостей в админке ж отсутствует. я думал мб сделать кнопку там где ник справа в навбаре, типа добавить новость, а далее модалка.

**Comment by roquie** [comment]
я не против кнопки и модалки, но куда ее засунуть? места в дропдауне твоем нет.

**Comment by viktor-melnikov** [comment]
а куда тогда? просто делать панель сбоку ради одной кнопку добавить твит...
может тогда ещё какие-то управляющие элементы туда вытащить

**Comment by roquie** [comment]
поч одной кнопки, там будет все что есть на главной + кнопка добавить ))

**Comment by viktor-melnikov** [comment]
всмысле всё что есть на главной?) я ща испугался=)

**Comment by roquie** [comment]
взять панель с новостями на главной, прикрутить к админке, добавить кнопку "добавление твита", сделать добавление и редактирование с аяксом

**Comment by viktor-melnikov** [comment]
редактирование???? вывести справа на панель все твиты и там сделать возможность их редактирования??????

**Comment by roquie** [comment]
ну да, в api же оно есть ) а также удаление

**Comment by viktor-melnikov** [comment]
просто мб для редактир и удаления сделать отдельную страницу? представь если будет много твитов, ютиться на маленькой панельке сбоку не оч удобно согласись

**Comment by roquie** [comment]
как вариант выводить только посл 3-5 твитов и только для них делать редактирование и удаление. Все остальное на сайте твиттера хай делает

**Comment by roquie** [comment]
тем более выводить все твиты у нас - это убийство - лаги будут страшные при большом их кол-ве

**Comment by viktor-melnikov** [comment]
ну окай) пусть будет 5 твитов последних и похуй вобще) сделать там ссылочку на twitter и пусть радуется:)

**Comment by roquie** [comment]
ага, это и надо

**Comment by viktor-melnikov** [comment]
и дело скорее не в лагах) а в кол-ве запросов к твиттеру)) там же ограничение у них вроде есть в месяц, ну на скоко я помню

**Comment by roquie** [comment]
ну и хер с ним, если до сдачи диплома возникнут проблемы, напишу парсер твитера

**Comment by viktor-melnikov** [comment]
)))) курлом брать будем хуль))) до диплома я думаю проблем не будет)))

**Comment by roquie** [comment]
ну вот и хорошо
