### ISSUE TITLE
превью для печати, некоторые заменить, а некоторые добавить

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#65]
https://drive.google.com/?tab=wo&authuser=0#folders/0B8du6mIw5FxlZUlROFRUeEVzaTg

должно быть 6, а не 4

**Comment by viktor-melnikov** [comment]
оки мэн)

**Comment by viktor-melnikov** [comment]
Превью "Письмо в МРЭО ГИБДД" нет, т.к. не открывается в проге документ.
