### ISSUE TITLE
добавить csrf токены для КАЖДОГО ajax и не аякс запроса на сервер

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#66]
задание для нас обоих. Касается безопасности, в первую очередь делать в лк и на главной...

``` php
<input type="hidden" name="csrf" value="<?=Security::token()?>"/>
```

**Comment by viktor-melnikov** [comment]
это сувать во все формы?

**Comment by roquie** [comment]
абсолютно во все формы и абсолютно во все jquery запросы к серверу.

**Comment by roquie** [comment]
запилил в админах для тестов. Как протестишь - пойдем глобально апдейтить лк
