### ISSUE TITLE
отображение ошибок форм

### ISSUE THREAD

**Issue by roquie** [roquie/autoschool#7]
![2013-10-02_162841](https://f.cloud.github.com/assets/3214290/1253145/41e229ee-2b5e-11e3-9969-f1d2f449c737.png)

**Comment by viktor-melnikov** [comment]
Что за хрень, откуда это такое????
ширина первого баллуна меньше ширины инпута, каким хером он залез????

**Comment by roquie** [comment]
без понятия, но залез

**Comment by viktor-melnikov** [comment]
расскажи симптомы при которых это случилось))

**Comment by roquie** [comment]
нажал кнопку отправить

**Comment by viktor-melnikov** [comment]
вот это бред конечно)) у меня там такое большое расстояние между ними) откуда они залезли друг на друга...

**Comment by viktor-melnikov** [comment]
fixed
